"""
Common fixtures for tests.

Fixture implementations are encouraged to use Resource.post(client) rather than
creating them through resource lists. This is to avoid unnecessary requests
to populate the list on access and refresh the list after adding resources to
them. This has the drawback of allowing the resource lists on the client and
resources becoming stale. ResourceList.expire() should be used to indicate the
resource lists should be refreshed on next access.
"""

from functools import wraps
from itertools import count
import os
from random import randint
from unittest import TestCase

import inspect
from typing import Callable


import kiln_controller.client as _client
from .mock_service import MockService
from kiln_controller.common.enums import PhaseType
from fixtures import kwargs

__all__ = [
    "mock_service_fixture",
    "MockService",
    "client_fixture",
    "user_fixture",
    "schedule_fixture",
    "phase_fixture",
]

SKIP_CLEANUP = os.getenv("SKIP_CLEANUP", "false").upper() == "TRUE"
PORT = int(os.getenv("SERVICE_PORT", "5000"))


def cleanup(func):
    """
    Fixture to cleanup the return value of the decorated fixture function.

    Fixture functions decorated with this accept a skip_cleanup kwarg that is
    intercepted by this fixture. If skip_cleanup is true-ish no cleanup will
    be performed by the fixture for the resource. This is useful for tests that
    delete a resource provided by a fixture.
    """

    @wraps(func)
    def _cleanable_fixture(*, mock_service, skip_cleanup=None, **kwargs):
        """wrapper to call func and register its return for cleanup"""
        resource = func(mock_service=mock_service, **kwargs)

        def _tearDown(*args, **kwargs):
            with mock_service.patch():
                resource.delete()

        def tearDown(*args, **kwargs):  # fixtures/kwargs cleanup callback
            if not (skip_cleanup or SKIP_CLEANUP):
                _tearDown(*args, **kwargs)

        resource.tearDown = tearDown
        resource._tearDown = _tearDown
        return resource

    return _cleanable_fixture


@kwargs.factory
def mock_service_fixture(**_) -> MockService:
    """fixture that provices a MockService"""
    return MockService()


@kwargs.factory
def client_fixture(
    mock_service: MockService,
    username: str = "admin",
    password: str = "admin",
    **_,
) -> _client.Client:
    """fixture that provides a Client"""
    with mock_service.patch():
        return _client.Client(username, password, port=PORT)


def unique_username(_user_count=count(randint(0, 9999) * 1000)) -> str:
    # todo - fix this janky way to create unique usernames. It is used to "make
    #        sure" tests don't use a username another test has leaked (should
    #        SKIP_CLEANUP be removed?).
    return f"username{next(_user_count)}"


@kwargs.factory
@cleanup
def user_fixture(
    name: str = "name",
    username: str | None = None,
    password: str | None = "password",
    skip_create: bool = False,
    mock_service: MockService | None = None,
    client: Client | None = None,
    _user_count: int = count(randint(0, 9999) * 1000),
    **kwargs: dict[str, Any],
):
    """
    Create a user.

    If username is not specified one is autogenerated to (hopefully) avoid
    conflict with existing user when running with LIVE_SERVICE=true. No attempt
    is made to actually ensure it doesn't conflict (it's random).

    skip_create causes the user to not be inserted (useful for when you need
    a user with a uniqueish username that hasn't been created on the server).
    """
    username = username or unique_username()
    user = _client.User(name, username, password)
    if not skip_create:
        with mock_service.patch():
            user.post(client)
    return user


@kwargs.factory
@cleanup
def device_fixture(
    mock_service,
    client,
    user,
    skip_create: bool = False,
    name="name",
    host="host",
    port=5000,
    url="/",
    **kwargs,
):
    device = _client.Device(name, user.id, host, port, url)
    if not skip_create:
        with mock_service.patch():
            device.post(client)
    return device


@kwargs.factory
@cleanup
def schedule_fixture(
    mock_service,
    client,
    user,
    skip_create: bool = False,
    name="name",
    **kwargs,
):
    schedule = _client.Schedule(name=name, user_id=user.id)
    if not skip_create:
        with mock_service.patch():
            schedule.post(client)
    return schedule


@kwargs.factory
def phase_fixture(
    mock_service,
    client,
    schedule,
    name="name",
    ordinal=0,
    phase_type=PhaseType.RAMP,
    duration=None,
    temperature=1000,
    rate=100,
    **kwargs,
):
    """
    Fixture to create a phase.

    By default, the phase is a 1 hour long 1000C constant phase with ordinal 0.

    Cleanup is managed by the schedule, phases from this fixture are not
    scheduled for cleanup.
    """

    phase = _client.Phase(
        name=name,
        ordinal=ordinal,
        phase_type=phase_type,
        temperature=temperature,
        rate=rate,
        parent=schedule,
    )
    with mock_service.patch():
        phase.post(client)
    return phase
