"""
Common fixtures for tests.

Fixture implementations are encouraged to use Resource.post(client) rather than
creating them through resource lists. This is to avoid unnecessary requests
to populate the list on access and refresh the list after adding resources to
them. This has the drawback of allowing the resource lists on the client and
resources becoming stale. ResourceList.expire() should be used to indicate the
resource lists should be refreshed on next access.
"""
# pylint: disable=unused-argument
# pylint: disable=redefined-outer-name


from functools import wraps
import os
from random import randint
from unittest import TestCase

from skytap.fixtures.fixtures import (default_fixture_name, pass_self,
                                      get_default_fixture_name)

from kiln_controller.client import Client, User, Schedule, Phase, Device
from kiln_controller.client.mock_service import MockService
from kiln_controller.common.enums import PhaseType


__all__ = ['CleanupTestCase',
           'mock_service_fixture',
           'client_fixture',
           'user_fixture',
           'schedule_fixture',
           'phase_fixture']


class CleanupTestCase(TestCase):
    """
    Mixin for adding cleanup functionality to tests.

    Primarily used by fixtures to remove resources created for tests, but test
    cases can also register resources for cleanup directly by calling:
    self.cleanup(mock_service, resource)

    SKIP_CLEANUP=true environment variable can be used to skip cleanup to allow
    inspection of the resources after the test completes.
    """
    def setUp(self):
        super().setUp()
        self._cleanup = []

    def tearDown(self):
        super().tearDown()
        for mock_service, resource in self._cleanup:
            with mock_service.patch():
                resource.delete()

    def cleanup(self, mock_service, resource):
        if os.getenv('SKIP_CLEANUP', 'false').upper() != 'TRUE':
            self._cleanup.append((mock_service, resource))


def cleanup(func):
    '''
    Fixture to cleanup the return value of the decorated fixture function.

    Fixture functions decorated with this accept a skip_cleanup kwarg that is
    intercepted by this fixture. If skip_cleanup is true-ish no cleanup will
    be performed by the fixture for the resource. This is useful for tests that
    delete a resource provided by a fixture.
    '''
    @wraps(func)
    def _cleanup(self, *, mock_service, skip_cleanup=None, **kwargs):
        '''wrapper to call func and register its return for cleanup'''
        resource = func(self, mock_service=mock_service, **kwargs)
        if not skip_cleanup:
            self.cleanup(mock_service, resource)
        return resource
    return _cleanup


@default_fixture_name('mock_service')
@pass_self
def mock_service_fixture(self, **_):
    '''fixture that provices a MockService'''
    return MockService()


@default_fixture_name('client')
@pass_self
def client_fixture(self, mock_service, **_):
    '''fixture that provides a Client'''
    with mock_service.patch():
        return Client()


@pass_self
@default_fixture_name('user')
@cleanup
def user_fixture(self, mock_service, client,
                 name='name', username=None, **kwargs):
    '''
    Create a user.

    If username is not specified one is autogenerated to (hopefully) avoid
    conflict with existing user when running with LIVE_SERVICE=true. No attempt
    is made to actually ensure it doesn't conflict (it's random).
    '''
    username = username or f"username{randint(1000, 9999)}"
    user = User(name, username)
    with mock_service.patch():
        user.post(client)
    return user


@pass_self
@default_fixture_name('device')
@cleanup
def device_fixture(self, mock_service, client,
                   name='name', host='host', port=5000, url='/',
                   user_kwarg=get_default_fixture_name(user_fixture),
                   **kwargs):
    user = kwargs[user_kwarg]
    device = Device(name, user.id, host, port, url)
    with mock_service.patch():
        device.post(client)
    return device


@pass_self
@default_fixture_name('schedule')
@cleanup
def schedule_fixture(self, mock_service, client,
                     user_kwarg=get_default_fixture_name(user_fixture),
                     name='name', **kwargs):
    user = kwargs[user_kwarg]
    schedule = Schedule(name=name, user_id=user.id)
    with mock_service.patch():
        schedule.post(client)
    return schedule


@pass_self
@default_fixture_name('phase')
def phase_fixture(self, mock_service, client,
                  schedule_kwarg=get_default_fixture_name(schedule_fixture),
                  name='name', ordinal=0, phase_type=PhaseType.CONSTANT,
                  duration=60, temperature=1000, rate=None, **kwargs):
    '''
    Fixture to create a phase.

    By default, the phase is a 1 hour long 1000C constant phase with ordinal 0.

    Cleanup is managed by the schedule, phases from this fixture are not
    scheduled for cleanup.
    '''

    schedule = kwargs[schedule_kwarg]
    phase = Phase(name=name, ordinal=ordinal, phase_type=phase_type,
                  temperature=temperature, rate=rate, parent=schedule)
    with mock_service.patch():
        phase.post(client)
    return phase
