"""
Common fixtures for tests.
"""
# pylint: disable=unused-argument
# pylint: disable=redefined-outer-name


from functools import wraps
import os
from random import randint
from unittest import TestCase

from skytap.fixtures.fixtures import (default_fixture_name, pass_self,
                                      get_default_fixture_name)

from kiln_controller.client import Client, User, Schedule
from kiln_controller.client.mock_service import MockService


__all__ = ['CleanupTestCase',
           'mock_service_fixture',
           'client_fixture',
           'user_fixture',
           'schedule_fixture']


class CleanupTestCase(TestCase):
    """
    Mixin for adding cleanup functionality to tests.

    Primarily used by fixtures to remove resources created for tests, but test
    cases can also register resources for cleanup directly by calling:
    self.cleanup(mock_service, resource)

    SKIP_CLEANUP=true environment variable can be used to skip cleanup to allow
    inspection of the resources after the test completes.
    """
    def setUp(self):
        super().setUp()
        self._cleanup = []

    def tearDown(self):
        super().tearDown()
        for mock_service, resource in self._cleanup:
            with mock_service.patch():
                resource.delete()

    def cleanup(self, mock_service, resource):
        if os.getenv('SKIP_CLEANUP', 'false').upper() != 'TRUE':
            self._cleanup.append((mock_service, resource))


def cleanup(func):
    '''fixture to cleanup the return value of the decorated fixture function'''
    @wraps(func)
    def _cleanup(self, *, mock_service, **kwargs):
        '''wrapper to call func and register its return for cleanup'''
        resource = func(self, mock_service=mock_service, **kwargs)
        self.cleanup(mock_service, resource)
        return resource
    return _cleanup


@default_fixture_name('mock_service')
@pass_self
def mock_service_fixture(self, **_):
    '''fixture that provices a MockService'''
    return MockService()


@default_fixture_name('client')
@pass_self
def client_fixture(self, mock_service, **_):
    '''fixture that provides a Client'''
    with mock_service.patch():
        return Client()


@pass_self
@default_fixture_name('user')
@cleanup
def user_fixture(self, client, name='name', username=None, **kwargs):
    '''
    Create a user.

    If username is not specified one is autogenerated to (hopefully) avoid
    conflict with existing user when running with LIVE_SERVICE=true. No attempt
    is made to actually ensure it doesn't conflict (it's random).
    '''
    username = username or f"username{randint(1000, 9999)}"
    user = User(name, username)
    client.users += user
    return user


@pass_self
@default_fixture_name('schedule')
@cleanup
def schedule_fixture(self, client,
                     user_kwarg=get_default_fixture_name(user_fixture),
                     name='name', **kwargs):
    user = kwargs[user_kwarg]
    schedule = Schedule(name=name, user_id=user.id)
    client.schedules += schedule
    return schedule

