[project]
name = "kiln_controller"
version = "0.1.0"
description = "Kiln Controller service"
readme = "README.md"
authors = [
    { name = "Lonnie Hutchinson", email = "chinacat@chinacat.org" }
]
requires-python = ">=3.14"
dependencies = [
    "aiofiles>=25.1.0",
    "fastapi[standard]>=0.141.1",
    "fixtures",
    "pydantic[email]>=2.13.4",
    "requests>=2.34.2",
    "sqlalchemy>=2.0.51",
    "sqlmodel>=0.0.39",
]

[build-system]
requires = ["uv_build>=0.11.9,<0.12.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "black>=26.5.1",
    "mypy>=2.3.0",
    "pyright>=1.1.411",
    "pytest>=9.1.1",
]

[tool.uv.sources]
fixtures = { path = "../../fixtures", editable = true }

[tool.pyright]
venvPath = "."
venv = ".venv"
